// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAazFnl2ov0V0ZlvCUQW7YgeulfQNtLRpc',
    appId: '1:16637933343:web:55b6526f619ae63395e22a',
    messagingSenderId: '16637933343',
    projectId: 'basicapp-45f62',
    authDomain: 'basicapp-45f62.firebaseapp.com',
    storageBucket: 'basicapp-45f62.appspot.com',
    measurementId: 'G-K5Y1TYZ2PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMb9HVnjfA9Z729JUbMyo83qWetzC--K4',
    appId: '1:16637933343:android:36e5428b59cbde3c95e22a',
    messagingSenderId: '16637933343',
    projectId: 'basicapp-45f62',
    storageBucket: 'basicapp-45f62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOaIsJ7jZxhegWgnRp29Zkkzuej98X7sk',
    appId: '1:16637933343:ios:8ec3fb2055c6158695e22a',
    messagingSenderId: '16637933343',
    projectId: 'basicapp-45f62',
    storageBucket: 'basicapp-45f62.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOaIsJ7jZxhegWgnRp29Zkkzuej98X7sk',
    appId: '1:16637933343:ios:a7f68357427713a995e22a',
    messagingSenderId: '16637933343',
    projectId: 'basicapp-45f62',
    storageBucket: 'basicapp-45f62.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
